from __future__ import annotations
from datetime import datetime, timedelta
import pandas as pd


def sample_findings_df() -> pd.DataFrame:
    now = datetime.now()
    data = [
        {"finding_id": "F-0001", "source": "Qualys", "asset": "SRV-FIN-01", "ip": "10.10.5.10", "os": "Windows Server 2019", "severity": "Critical", "cvss": 10.0, "cve": "CVE-2020-0796", "title": "SMBv3 Remote Code Execution", "status": "Open", "exploitability": "High", "business_service": "Finanzas", "patch_available": True, "first_seen": now - timedelta(days=5), "last_seen": now - timedelta(hours=3), "description": "Se detecta exposición del servicio SMB con vulnerabilidad crítica conocida.", "recommendation": "Validar versión, deshabilitar SMBv1, segmentar red y aplicar parche aprobado."},
        {"finding_id": "F-0002", "source": "Tenable", "asset": "APP-CRM-02", "ip": "10.10.20.12", "os": "Ubuntu 22.04", "severity": "High", "cvss": 8.8, "cve": "CVE-2021-44228", "title": "Log4Shell detectado en componente Java", "status": "Open", "exploitability": "High", "business_service": "Comercial", "patch_available": True, "first_seen": now - timedelta(days=12), "last_seen": now - timedelta(hours=7), "description": "Componente vulnerable de logging identificado en aplicación de atención comercial.", "recommendation": "Actualizar librería Log4j, validar dependencias transitivas y revisar IOC asociados."},
        {"finding_id": "F-0003", "source": "Qualys", "asset": "WEB-PQRS-01", "ip": "10.10.30.15", "os": "Red Hat Enterprise Linux 8", "severity": "Medium", "cvss": 6.4, "cve": "CVE-2023-12345", "title": "TLS débil y suite criptográfica obsoleta", "status": "Mitigation Planned", "exploitability": "Medium", "business_service": "PQRS", "patch_available": False, "first_seen": now - timedelta(days=20), "last_seen": now - timedelta(days=1), "description": "El servicio acepta cifrados heredados y protocolos no recomendados.", "recommendation": "Endurecer configuración TLS, retirar suites heredadas y revalidar con escaneo."},
        {"finding_id": "F-0004", "source": "Tenable", "asset": "DB-FACT-01", "ip": "10.10.40.5", "os": "Oracle Linux 8", "severity": "High", "cvss": 7.5, "cve": "CVE-2022-99999", "title": "Puerto administrativo expuesto", "status": "Open", "exploitability": "Medium", "business_service": "Facturación", "patch_available": False, "first_seen": now - timedelta(days=8), "last_seen": now - timedelta(hours=20), "description": "Puerto administrativo accesible desde segmento no autorizado.", "recommendation": "Aplicar hardening de red, listas de control y segmentación administrativa."},
        {"finding_id": "F-0005", "source": "Qualys", "asset": "SCADA-GTW-01", "ip": "10.20.1.25", "os": "Windows Server 2016", "severity": "Critical", "cvss": 9.8, "cve": "CVE-2019-0708", "title": "BlueKeep en gateway OT", "status": "Open", "exploitability": "High", "business_service": "Operación OT", "patch_available": True, "first_seen": now - timedelta(days=2), "last_seen": now - timedelta(hours=1), "description": "Gateway OT presenta condición crítica con posible impacto operativo.", "recommendation": "Aislar activo, aplicar parche validado, reforzar monitoreo y ventana controlada de cambio."},
        {"finding_id": "F-0006", "source": "Tenable", "asset": "MAIL-EDGE-01", "ip": "10.10.50.33", "os": "Windows Server 2022", "severity": "Low", "cvss": 3.7, "cve": "CVE-2024-0101", "title": "Banner disclosure", "status": "Accepted Risk", "exploitability": "Low", "business_service": "Correo", "patch_available": False, "first_seen": now - timedelta(days=60), "last_seen": now - timedelta(days=5), "description": "El servicio expone versión en cabeceras, sin hallazgo adicional asociado.", "recommendation": "Ocultar banner en próxima ventana de mantenimiento."},
    ]
    return pd.DataFrame(data)


def sample_knowledge_base() -> list[dict]:
    return [
        {"doc_id": "KB-001", "title": "Playbook - Priorización de vulnerabilidades críticas", "category": "Playbook", "tags": ["priorización", "cvss", "activo crítico"], "content": "Priorizar hallazgos críticos con CVSS >= 9, explotación pública y activos que soportan procesos de facturación, finanzas u operación OT. Escalar a atención en 0-24 horas."},
        {"doc_id": "KB-002", "title": "Guía - Remediación de Log4Shell", "category": "Guía técnica", "tags": ["log4shell", "java", "parches"], "content": "Actualizar Log4j a versión segura, validar dependencias transitivas, revisar indicadores de compromiso y confirmar por inventario de activos Java."},
        {"doc_id": "KB-003", "title": "Procedimiento - Hardening TLS", "category": "Procedimiento", "tags": ["tls", "cifrado", "hardening"], "content": "Deshabilitar TLS 1.0 y 1.1, remover suites heredadas, exigir certificados vigentes y ejecutar reescaneo posterior para validar cumplimiento."},
        {"doc_id": "KB-004", "title": "Arquitectura - Modelo híbrido EMCALI Cyber 2.0", "category": "Arquitectura", "tags": ["rag", "modelo local", "vector db", "cloud"], "content": "El flujo híbrido recomendado es: fuente Qualys/Tenable/CSV, normalización JSON, recuperación RAG, inferencia local con Ollama o inferencia cloud controlada, y salida validada para el analista."},
        {"doc_id": "KB-005", "title": "Métrica - Evaluación del agente LLM", "category": "Métricas", "tags": ["precision", "recall", "alucinación", "ttft"], "content": "Para evaluar el agente se recomienda medir precision, recall, pass@1, tasa de alucinación, attack success rate, latencia TTFT y tokens por segundo."},
    ]
